# Generated by Django 4.2.23 on 2025-07-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='times_shortened',
        ),
    ]
