# Generated by Django 4.2.23 on 2025-07-15 04:22

from django.db import migrations, models
import shortner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_remove_shortenedurl_times_shortened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(help_text='Enter a valid URL (e.g., https://example.com).', max_length=2000, validators=[shortner.models.validate_url]),
        ),
    ]
